spring:
  datasource:
    url: jdbc:sqlserver://jnote.database.windows.net:1433;database=jnote-db;user=jnote473@jnote;password={Jnotedbpass473};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;